sudo: required
dist: trusty

language: node_js
node_js:
  - "6"
  - "6.1"
  - "6.0"
  - "5"
  - "4"
  - "4.4"
  - "4.3"
  - "4.2"
  - "4.1"
  - "4.0"

script: "npm run test-travis"

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
    code_climate:
        repo_token: ddcb9c76db9f8ec90db2b713427c5a2713609f3a4c68bc11b9c1ad423839de04
